version: "3"

services:
  imageuploader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imageUploader
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.imageUploader.entrypoints=websecure
      - traefik.http.routers.imageUploader.rule=Host(`imageUploader.p.kariukigeorge.me`)
      - traefik.http.routers.imageUploader.tls.certresolver=lets-encrypt
      - traefik.http.services.imageUploader.loadbalancer.server.port=3000
    networks:
      - traefik
    restart: unless-stopped

    env_file: ./.env

networks:
  traefik:
    external: true
